if (typeof vimeowrap === 'undefined') {/*

 Vimeo Wrap

 Author: Wesley Luyten
 Version: 1.1 - (2012/06/07)
*/
var vimeowrap=function(b){return vimeowrap.api.select(b)};
(function(b){var f={};b.api=function(c){function e(d){g=d;f(d[a.config.item].url)}function f(d){b.utils.jsonp("http://vimeo.com/api/oembed.json",h({url:d}),function(d){var g=document.createElement("div");g.innerHTML=d.html;a.iframe=g.children[0];a.iframe.id=a.config.player_id;b.utils.css(a.iframe,{position:"absolute",display:"none"});d=function(){b.utils.css(a.iframe,{display:"block"})};a.iframe.attachEvent?a.iframe.attachEvent("onload",d):a.iframe.onload=d;b.utils.prepend(a.iframe,a.display);b.Froogaloop(a.iframe.id).addEvent("ready",
function(){a.player=b.Froogaloop(a.iframe.id);a.events.playerReady.dispatch(a.player);a.player.addEvent("finish",i)})})}function h(d){for(var g="url,width,maxwidth,height,maxheight,byline,title,portrait,color,callback,autoplay,loop,xhtml,api,wmode,iframe,player_id".split(","),e=0;e<g.length;e++){var c=g[e];a.config.hasOwnProperty(c)&&(d[c]=a.config[c])}return d}function i(){var d;switch(a.config.repeat){case "list":d=a.config.item+1;d<g.length&&a.playlistItem(d,!0);break;case "always":d=a.config.item+
1;d>=g.length&&(d=0);a.playlistItem(d,!0);break;case "single":a.play()}}var a=this,g=null;this.container=c;this.id=c.id;this.config=this.player=this.iframe=this.display=null;this.plugins={};this.setup=function(d){var g={width:480,height:280,color:"00adef",repeat:"none",item:0,api:!0,player_id:b.utils.uniqueId("player_")};a.config=b.utils.extend(g,d);a.container.innerHTML="";b.utils.css(a.container,{position:"relative"});a.display=document.createElement("div");a.display.id=a.id+"_display";a.container.appendChild(a.display);
b.utils.css(a.display,{width:a.config.width,height:a.config.height,position:"absolute",background:"#000000"});var d=a.config.height,g=0,c;for(c in a.config.plugins)"function"===typeof b[c]&&(a.plugins[c]=new b[c](a,a.config.plugins[c]),a.plugins[c].config.y=d,d+=a.plugins[c].config.height||0,"top"===a.plugins[c].config.position&&(a.plugins[c].config.y=g,g+=a.plugins[c].config.height),a.plugins[c].setup());b.utils.css(a.container,{width:a.config.width,height:d});b.utils.css(a.display,{top:g});a.events.playlist.add(e);
(new b.playlistloader(a)).load(a.config.urls)};this.playlistItem=function(d,c){a.config.item=d;a.pause();b.utils.css(a.iframe,{display:"none"});"boolean"===typeof c&&(a.config.autoplay=c);for(var e="http://player.vimeo.com/video/"+g[d].id+"?",f="byline,title,portrait,color,autoplay,loop,api,player_id".split(","),j=0;j<f.length;j++){var h=f[j];if(a.config.hasOwnProperty(h)){var i=a.config[h];"boolean"===typeof i&&(i=i?1:0);e+=encodeURIComponent(h)+"="+encodeURIComponent(i)+"&"}}a.iframe&&(a.iframe.src=
e.slice(0,-1))};this.play=function(){a.player&&a.player.api("paused",function(d){!0===d&&a.player.api("play")})};this.pause=function(){a.player&&a.player.api("paused",function(d){!1===d&&a.player.api("pause")})};this.onPlay=function(d){a.player&&a.player.addEvent("play",d)};this.onPause=function(d){a.player&&a.player.addEvent("pause",d)};this.onFinish=function(d){a.player&&a.player.addEvent("finish",d)};this.events={playerReady:new b.signal,playlist:new b.signal}};b.api.select=function(c){var e;c.nodeType?
e=c:"string"===typeof c&&(e=document.getElementById(c));return e?(c=f[e.id])?c:f[e.id]=new b.api(e):null}})(vimeowrap);(function(b){b.playlistloader=function(f){function c(){b.utils.jsonp(j.list[h++],{},e)}function e(a){i=i.concat(a);h<j.list.length?c():(f.events.playlist.dispatch(i),f.events.playlist.remove())}var j=this,h=0,i=[];this.load=function(a){for(var g=j,d=0;d<a.length;d++)a[d]=a[d].replace(/vimeo.com\/(\d+)$/i,"vimeo.com/api/v2/video/$1.json"),a[d]=a[d].replace(/vimeo.com\/([A-Z0-9]+)$/i,"vimeo.com/api/v2/$1/videos.json"),a[d]=a[d].replace(/vimeo.com\/groups\/([A-Z0-9]+)$/i,"vimeo.com/api/v2/group/$1/videos.json"),
a[d]=a[d].replace(/vimeo.com\/channels\/([A-Z0-9]+)$/i,"vimeo.com/api/v2/channel/$1/videos.json"),a[d]=a[d].replace(/vimeo.com\/album\/([A-Z0-9]+)$/i,"vimeo.com/api/v2/album/$1/videos.json");g.list=a;c();return i}}})(vimeowrap);(function(b){b.utils=function(){};b.utils.jsonp=function(c,e,f){var h="?",e=e||{},i;for(i in e)e.hasOwnProperty(i)&&(h+=encodeURIComponent(i)+"="+encodeURIComponent(e[i])+"&");var a=b.utils.uniqueId("json_call");window[a]=function(d){f(d);window[a]=null};var g=document.createElement("script");g.src=c+h+"callback="+a;g.async=!0;g.onload=g.onreadystatechange=function(){if(!this.readyState||"loaded"===this.readyState||"complete"===this.readyState)g.onload=g.onreadystatechange=null,g&&g.parentNode&&g.parentNode.removeChild(g)};
c=document.head||document.getElementsByTagName("head")[0]||document.documentElement;c.insertBefore(g,c.firstChild)};b.utils.extend=function(c,e){for(var b in e)e[b]&&e[b].constructor&&e[b].constructor===Object?(c[b]=c[b]||{},arguments.callee(c[b],e[b])):c[b]=e[b];return c};b.utils.css=function(c,e){if(c)for(var b in e)try{if("undefined"!==typeof e[b]){if("number"==typeof e[b]&&!("zIndex"==b||"opacity"==b)){if(isNaN(e[b]))continue;e[b]=Math.ceil(e[b])+"px"}c.style[b]=e[b]}}catch(f){}};b.utils.prepend=
function(c,b){b.firstChild?b.insertBefore(c,b.firstChild):b.appendChild(c)};var f=0;b.utils.uniqueId=function(b){var e=f++;return b?b+e:e}})(vimeowrap);Array.indexOf||(Array.prototype.indexOf=function(b){for(var f=0;f<this.length;f++)if(this[f]==b)return f;return-1});String.prototype.populate=function(b){return this.replace(/\{\{\s*([^\s}]+)\s*\}\}/g,function(f,c){c=c.replace(/\|/g,"_");return typeof b[c]!=="undefined"?b[c]:f})};(function(b){b.signal=function(){var b=[];this.add=function(c){b.push(c)};this.dispatch=function(){for(var c=Array.prototype.slice.call(arguments),e=0;e<b.length;e++)"function"===typeof b[e]&&b[e].apply(this,c)};this.remove=function(c){if(c)for(var e=0;e<b.length;e++)b[e]===c&&(b.splice(e,1),e--);else b=[]}}})(vimeowrap);/*

 Vimeo Froogaloop
*/
(function(b){function f(a){return new f.fn.init(a)}function c(a,d,b){if(!b.contentWindow.postMessage)return!1;var c=b.getAttribute("src").split("?")[0],a=JSON.stringify({method:a,value:d});"//"===c.substr(0,2)&&(c=window.location.protocol+c);b.contentWindow.postMessage(a,c)}function e(b){var d,c;try{d=JSON.parse(b.data),c=d.event||d.method}catch(e){}"ready"==c&&!i&&(i=!0);if("undefined"===typeof d||b.origin!=a)return!1;var b=d.value,f=d.data,j=""===j?null:d.player_id;d=j?h[j][c]:h[c];c=[];if(!d)return!1;
void 0!==b&&c.push(b);f&&c.push(f);j&&c.push(j);return 0<c.length?d.apply(null,c):d.call()}function j(a,d,b){b?(h[b]||(h[b]={}),h[b][a]=d):h[a]=d}var h={},i=!1,a="";f.fn=f.prototype={element:null,init:function(b){"string"===typeof b&&(b=document.getElementById(b));this.element=b;b=this.element.getAttribute("src");"//"===b.substr(0,2)&&(b=window.location.protocol+b);for(var b=b.split("/"),d="",c=0,e=b.length;c<e;c++){if(3>c)d+=b[c];else break;2>c&&(d+="/")}a=d;return this},api:function(b,a){if(!this.element||
!b)return!1;var e=this.element,f=""!==e.id?e.id:null,h=!a||!a.constructor||!a.call||!a.apply?a:null,i=a&&a.constructor&&a.call&&a.apply?a:null;i&&j(b,i,f);c(b,h,e);return this},addEvent:function(a,b){if(!this.element)return!1;var e=this.element,f=""!==e.id?e.id:null;j(a,b,f);"ready"!=a?c("addEventListener",a,e):"ready"==a&&i&&b.call(null,f);return this},removeEvent:function(a){if(!this.element)return!1;var b=this.element,e;a:{if((e=""!==b.id?b.id:null)&&h[e]){if(!h[e][a]){e=!1;break a}h[e][a]=null}else{if(!h[a]){e=
!1;break a}h[a]=null}e=!0}"ready"!=a&&e&&c("removeEventListener",a,b)}};f.fn.init.prototype=f.fn;window.addEventListener?window.addEventListener("message",e,!1):window.attachEvent("onmessage",e);return b.Froogaloop=b.$f=f})(vimeowrap);}
