if (typeof vimeowrap === 'undefined') {/*

 Vimeo Wrap

 Author: Wesley Luyten
 Version: 1.1 - (2012/06/07)
*/
var vimeowrap=function(a){return vimeowrap.api.select(a)};
(function(a){var f={};a.api=function(b){function e(c){g=c;f(c[d.config.item].url)}function f(c){a.utils.jsonp("http://vimeo.com/api/oembed.json",h({url:c}),function(c){var g=document.createElement("div");g.innerHTML=c.html;d.player=g.children[0];d.player.id=d.config.player_id;a.utils.css(d.player,{position:"absolute",display:"none"});c=function(){a.utils.css(d.player,{display:"block"})};d.player.attachEvent?d.player.attachEvent("onload",c):d.player.onload=c;a.utils.prepend(d.player,d.display);a.Froogaloop(d.player.id).addEvent("ready",
function(){d.froogaloop=a.Froogaloop(d.player.id);d.events.froogaloopReady.dispatch(d.froogaloop);d.froogaloop.addEvent("finish",i)})})}function h(c){for(var g="url,width,maxwidth,height,maxheight,byline,title,portrait,color,callback,autoplay,loop,xhtml,api,wmode,iframe,player_id".split(","),e=0;e<g.length;e++){var b=g[e];d.config.hasOwnProperty(b)&&(c[b]=d.config[b])}return c}function i(){var c;switch(d.config.repeat){case "list":c=d.config.item+1;c<g.length&&d.playlistItem(c,!0);break;case "always":c=
d.config.item+1,c>=g.length&&(c=0),d.playlistItem(c,!0)}}var d=this,g=null;this.container=b;this.id=b.id;this.config=this.player=this.display=null;this.plugins={};this.froogaloop=null;this.setup=function(c){var g={width:480,height:280,color:"00adef",repeat:"none",item:0,api:!0,player_id:a.utils.uniqueId("player_")};this.config=a.utils.extend(g,c);d.container.innerHTML="";a.utils.css(d.container,{position:"relative"});d.display=document.createElement("div");d.display.id=d.id+"_display";d.container.appendChild(d.display);
a.utils.css(d.display,{width:d.config.width,height:d.config.height,position:"absolute",background:"#000000"});var c=this.config.height,g=0,b;for(b in this.config.plugins)"function"===typeof a[b]&&(this.plugins[b]=new a[b](this,this.config.plugins[b]),this.plugins[b].config.y=c,c+=this.plugins[b].config.height,"top"===this.plugins[b].config.position&&(this.plugins[b].config.y=g,g+=this.plugins[b].config.height),this.plugins[b].setup());a.utils.css(d.container,{width:d.config.width,height:c});a.utils.css(d.display,
{top:g});this.events.playlist.add(e);(new a.playlistloader(this)).load(this.config.urls)};this.playlistItem=function(c,b){if(c!==d.config.item){this.pause();d.config.item=c;a.utils.css(d.player,{display:"none"});"boolean"===typeof b&&(this.config.autoplay=b);for(var e="http://player.vimeo.com/video/"+g[c].id+"?",f="byline,title,portrait,color,autoplay,loop,api,player_id".split(","),j=0;j<f.length;j++){var h=f[j];if(this.config.hasOwnProperty(h)){var i=d.config[h];"boolean"===typeof i&&(i=i?1:0);e+=
encodeURIComponent(h)+"="+encodeURIComponent(i)+"&"}}this.player&&(this.player.src=e.slice(0,-1))}};this.play=function(){d.froogaloop&&d.froogaloop.api("paused",function(c){!0===c&&d.froogaloop.api("play")})};this.pause=function(){d.froogaloop&&d.froogaloop.api("paused",function(c){!1===c&&d.froogaloop.api("pause")})};this.events={froogaloopReady:new a.signal,playlist:new a.signal}};a.api.select=function(b){var e;b.nodeType?e=b:"string"===typeof b&&(e=document.getElementById(b));return e?(b=f[e.id])?
b:f[e.id]=new a.api(e):null}})(vimeowrap);(function(a){a.playlistloader=function(f){function b(){a.utils.jsonp(j.list[h++],{},e)}function e(d){i=i.concat(d);h<j.list.length?b():(f.events.playlist.dispatch(i),f.events.playlist.remove())}var j=this,h=0,i=[];this.load=function(d){for(var g=j,c=0;c<d.length;c++)d[c]=d[c].replace(/vimeo.com\/(\d+)$/i,"vimeo.com/api/v2/video/$1.json"),d[c]=d[c].replace(/vimeo.com\/([A-Z][A-Z0-9]+)$/i,"vimeo.com/api/v2/$1/videos.json");g.list=d;b();return i}}})(vimeowrap);(function(a){a.utils=function(){};a.utils.jsonp=function(b,e,f){var h="?",e=e||{},i;for(i in e)e.hasOwnProperty(i)&&(h+=encodeURIComponent(i)+"="+encodeURIComponent(e[i])+"&");var d=a.utils.uniqueId("vimeojson");window[d]=function(c){f(c);window[d]=null};var g=document.createElement("script");g.src=b+h+"callback="+d;g.async=!0;g.onload=g.onreadystatechange=function(){if(!this.readyState||"loaded"===this.readyState||"complete"===this.readyState)g.onload=g.onreadystatechange=null,g&&g.parentNode&&g.parentNode.removeChild(g)};
b=document.head||document.getElementsByTagName("head")[0]||document.documentElement;b.insertBefore(g,b.firstChild)};a.utils.extend=function(b,e){for(var a in e)e[a]&&e[a].constructor&&e[a].constructor===Object?(b[a]=b[a]||{},arguments.callee(b[a],e[a])):b[a]=e[a];return b};a.utils.css=function(b,e){if(b)for(var a in e)try{if("undefined"!==typeof e[a]){if("number"==typeof e[a]&&!("zIndex"==a||"opacity"==a)){if(isNaN(e[a]))continue;e[a]=Math.ceil(e[a])+"px"}b.style[a]=e[a]}}catch(f){}};a.utils.prepend=
function(b,a){a.firstChild?a.insertBefore(b,a.firstChild):a.appendChild(b)};var f=0;a.utils.uniqueId=function(a){var e=f++;return a?a+e:e}})(vimeowrap);Array.indexOf||(Array.prototype.indexOf=function(a){for(var f=0;f<this.length;f++)if(this[f]==a)return f;return-1});String.prototype.populate=function(a){return this.replace(/\{\{\s*([^\s}]+)\s*\}\}/g,function(f,b){b=b.replace(/\|/g,"_");return typeof a[b]!=="undefined"?a[b]:f})};(function(a){a.signal=function(){var a=[];this.add=function(b){a.push(b)};this.dispatch=function(){for(var b=Array.prototype.slice.call(arguments),e=0;e<a.length;e++)"function"===typeof a[e]&&a[e].apply(this,b)};this.remove=function(b){if(b)for(var e=0;e<a.length;e++)a[e]===b&&(a.splice(e,1),e--);else a=[]}}})(vimeowrap);/*

 Vimeo Froogaloop
*/
(function(a){function f(a){return new f.fn.init(a)}function b(a,c,b){if(!b.contentWindow.postMessage)return!1;var d=b.getAttribute("src").split("?")[0],a=JSON.stringify({method:a,value:c});"//"===d.substr(0,2)&&(d=window.location.protocol+d);b.contentWindow.postMessage(a,d)}function e(a){var c,b;try{c=JSON.parse(a.data),b=c.event||c.method}catch(e){}"ready"==b&&!i&&(i=!0);if("undefined"===typeof c||a.origin!=d)return!1;var a=c.value,f=c.data,j=""===j?null:c.player_id;c=j?h[j][b]:h[b];b=[];if(!c)return!1;
void 0!==a&&b.push(a);f&&b.push(f);j&&b.push(j);return 0<b.length?c.apply(null,b):c.call()}function j(a,c,b){b?(h[b]||(h[b]={}),h[b][a]=c):h[a]=c}var h={},i=!1,d="";f.fn=f.prototype={element:null,init:function(a){"string"===typeof a&&(a=document.getElementById(a));this.element=a;a=this.element.getAttribute("src");"//"===a.substr(0,2)&&(a=window.location.protocol+a);for(var a=a.split("/"),c="",b=0,e=a.length;b<e;b++){if(3>b)c+=a[b];else break;2>b&&(c+="/")}d=c;return this},api:function(a,c){if(!this.element||
!a)return!1;var d=this.element,e=""!==d.id?d.id:null,f=!c||!c.constructor||!c.call||!c.apply?c:null,h=c&&c.constructor&&c.call&&c.apply?c:null;h&&j(a,h,e);b(a,f,d);return this},addEvent:function(a,c){if(!this.element)return!1;var d=this.element,e=""!==d.id?d.id:null;j(a,c,e);"ready"!=a?b("addEventListener",a,d):"ready"==a&&i&&c.call(null,e);return this},removeEvent:function(a){if(!this.element)return!1;var c=this.element,d;a:{if((d=""!==c.id?c.id:null)&&h[d]){if(!h[d][a]){d=!1;break a}h[d][a]=null}else{if(!h[a]){d=
!1;break a}h[a]=null}d=!0}"ready"!=a&&d&&b("removeEventListener",a,c)}};f.fn.init.prototype=f.fn;window.addEventListener?window.addEventListener("message",e,!1):window.attachEvent("onmessage",e);return a.Froogaloop=a.$f=f})(vimeowrap);}
