if (typeof vimeowrap === 'undefined') {/*

 Vimeo Wrap

 Author: Wesley Luyten
 Version: 1.1 - (2012/06/07)
*/
var vimeowrap=function(a){return vimeowrap.api.select(a)};
(function(a){var f={};a.api=function(c){function d(e){g=e;f(e[b.config.item].url)}function f(e){a.utils.jsonp("http://vimeo.com/api/oembed.json",h({url:e}),function(e){var g=document.createElement("div");g.innerHTML=e.html;b.player=g.children[0];b.player.id=b.config.player_id;a.utils.css(b.player,{position:"absolute",display:"none"});e=function(){a.utils.css(b.player,{display:"block"})};b.player.attachEvent?b.player.attachEvent("onload",e):b.player.onload=e;a.utils.prepend(b.player,b.display);a.Froogaloop(b.player.id).addEvent("ready",
function(){b.froogaloop=a.Froogaloop(b.player.id);b.events.froogaloopReady.dispatch(b.froogaloop);b.froogaloop.addEvent("finish",i)})})}function h(e){for(var g="url,width,maxwidth,height,maxheight,byline,title,portrait,color,callback,autoplay,loop,xhtml,api,wmode,iframe,player_id".split(","),d=0;d<g.length;d++){var c=g[d];b.config.hasOwnProperty(c)&&(e[c]=b.config[c])}return e}function i(){var e;switch(b.config.repeat){case "list":e=b.config.item+1;e<g.length&&b.playlistItem(e,!0);break;case "always":e=
b.config.item+1,e>=g.length&&(e=0),b.playlistItem(e,!0)}}var b=this,g=null;this.container=c;this.id=c.id;this.config=this.player=this.display=null;this.plugins={};this.froogaloop=null;this.setup=function(e){var g={width:480,height:280,color:"00adef",repeat:"none",item:0,api:!0,player_id:a.utils.uniqueId("player_")};b.config=a.utils.extend(g,e);b.container.innerHTML="";a.utils.css(b.container,{position:"relative"});b.display=document.createElement("div");b.display.id=b.id+"_display";b.container.appendChild(b.display);
a.utils.css(b.display,{width:b.config.width,height:b.config.height,position:"absolute",background:"#000000"});var e=b.config.height,g=0,c;for(c in b.config.plugins)"function"===typeof a[c]&&(b.plugins[c]=new a[c](b,b.config.plugins[c]),b.plugins[c].config.y=e,e+=b.plugins[c].config.height,"top"===b.plugins[c].config.position&&(b.plugins[c].config.y=g,g+=b.plugins[c].config.height),b.plugins[c].setup());a.utils.css(b.container,{width:b.config.width,height:e});a.utils.css(b.display,{top:g});b.events.playlist.add(d);
(new a.playlistloader(b)).load(b.config.urls)};this.playlistItem=function(e,c){b.config.item=e;b.pause();a.utils.css(b.player,{display:"none"});"boolean"===typeof c&&(b.config.autoplay=c);for(var d="http://player.vimeo.com/video/"+g[e].id+"?",f="byline,title,portrait,color,autoplay,loop,api,player_id".split(","),j=0;j<f.length;j++){var h=f[j];if(b.config.hasOwnProperty(h)){var i=b.config[h];"boolean"===typeof i&&(i=i?1:0);d+=encodeURIComponent(h)+"="+encodeURIComponent(i)+"&"}}b.player&&(b.player.src=
d.slice(0,-1))};this.play=function(){b.froogaloop&&b.froogaloop.api("paused",function(e){!0===e&&b.froogaloop.api("play")})};this.pause=function(){b.froogaloop&&b.froogaloop.api("paused",function(e){!1===e&&b.froogaloop.api("pause")})};this.events={froogaloopReady:new a.signal,playlist:new a.signal}};a.api.select=function(c){var d;c.nodeType?d=c:"string"===typeof c&&(d=document.getElementById(c));return d?(c=f[d.id])?c:f[d.id]=new a.api(d):null}})(vimeowrap);(function(a){a.playlistloader=function(f){function c(){a.utils.jsonp(j.list[h++],{},d)}function d(b){i=i.concat(b);h<j.list.length?c():(f.events.playlist.dispatch(i),f.events.playlist.remove())}var j=this,h=0,i=[];this.load=function(b){for(var g=j,e=0;e<b.length;e++)b[e]=b[e].replace(/vimeo.com\/(\d+)$/i,"vimeo.com/api/v2/video/$1.json"),b[e]=b[e].replace(/vimeo.com\/([A-Z][A-Z0-9]+)$/i,"vimeo.com/api/v2/$1/videos.json");g.list=b;c();return i}}})(vimeowrap);(function(a){a.utils=function(){};a.utils.jsonp=function(c,d,f){var h="?",d=d||{},i;for(i in d)d.hasOwnProperty(i)&&(h+=encodeURIComponent(i)+"="+encodeURIComponent(d[i])+"&");var b=a.utils.uniqueId("vimeojson");window[b]=function(e){f(e);window[b]=null};var g=document.createElement("script");g.src=c+h+"callback="+b;g.async=!0;g.onload=g.onreadystatechange=function(){if(!this.readyState||"loaded"===this.readyState||"complete"===this.readyState)g.onload=g.onreadystatechange=null,g&&g.parentNode&&g.parentNode.removeChild(g)};
c=document.head||document.getElementsByTagName("head")[0]||document.documentElement;c.insertBefore(g,c.firstChild)};a.utils.extend=function(c,d){for(var a in d)d[a]&&d[a].constructor&&d[a].constructor===Object?(c[a]=c[a]||{},arguments.callee(c[a],d[a])):c[a]=d[a];return c};a.utils.css=function(c,d){if(c)for(var a in d)try{if("undefined"!==typeof d[a]){if("number"==typeof d[a]&&!("zIndex"==a||"opacity"==a)){if(isNaN(d[a]))continue;d[a]=Math.ceil(d[a])+"px"}c.style[a]=d[a]}}catch(f){}};a.utils.prepend=
function(c,a){a.firstChild?a.insertBefore(c,a.firstChild):a.appendChild(c)};var f=0;a.utils.uniqueId=function(a){var d=f++;return a?a+d:d}})(vimeowrap);Array.indexOf||(Array.prototype.indexOf=function(a){for(var f=0;f<this.length;f++)if(this[f]==a)return f;return-1});String.prototype.populate=function(a){return this.replace(/\{\{\s*([^\s}]+)\s*\}\}/g,function(f,c){c=c.replace(/\|/g,"_");return typeof a[c]!=="undefined"?a[c]:f})};(function(a){a.signal=function(){var a=[];this.add=function(c){a.push(c)};this.dispatch=function(){for(var c=Array.prototype.slice.call(arguments),d=0;d<a.length;d++)"function"===typeof a[d]&&a[d].apply(this,c)};this.remove=function(c){if(c)for(var d=0;d<a.length;d++)a[d]===c&&(a.splice(d,1),d--);else a=[]}}})(vimeowrap);/*

 Vimeo Froogaloop
*/
(function(a){function f(b){return new f.fn.init(b)}function c(b,e,a){if(!a.contentWindow.postMessage)return!1;var c=a.getAttribute("src").split("?")[0],b=JSON.stringify({method:b,value:e});"//"===c.substr(0,2)&&(c=window.location.protocol+c);a.contentWindow.postMessage(b,c)}function d(a){var e,c;try{e=JSON.parse(a.data),c=e.event||e.method}catch(d){}"ready"==c&&!i&&(i=!0);if("undefined"===typeof e||a.origin!=b)return!1;var a=e.value,f=e.data,j=""===j?null:e.player_id;e=j?h[j][c]:h[c];c=[];if(!e)return!1;
void 0!==a&&c.push(a);f&&c.push(f);j&&c.push(j);return 0<c.length?e.apply(null,c):e.call()}function j(a,b,c){c?(h[c]||(h[c]={}),h[c][a]=b):h[a]=b}var h={},i=!1,b="";f.fn=f.prototype={element:null,init:function(a){"string"===typeof a&&(a=document.getElementById(a));this.element=a;a=this.element.getAttribute("src");"//"===a.substr(0,2)&&(a=window.location.protocol+a);for(var a=a.split("/"),c="",d=0,f=a.length;d<f;d++){if(3>d)c+=a[d];else break;2>d&&(c+="/")}b=c;return this},api:function(a,b){if(!this.element||
!a)return!1;var d=this.element,f=""!==d.id?d.id:null,h=!b||!b.constructor||!b.call||!b.apply?b:null,i=b&&b.constructor&&b.call&&b.apply?b:null;i&&j(a,i,f);c(a,h,d);return this},addEvent:function(a,b){if(!this.element)return!1;var d=this.element,f=""!==d.id?d.id:null;j(a,b,f);"ready"!=a?c("addEventListener",a,d):"ready"==a&&i&&b.call(null,f);return this},removeEvent:function(a){if(!this.element)return!1;var b=this.element,d;a:{if((d=""!==b.id?b.id:null)&&h[d]){if(!h[d][a]){d=!1;break a}h[d][a]=null}else{if(!h[a]){d=
!1;break a}h[a]=null}d=!0}"ready"!=a&&d&&c("removeEventListener",a,b)}};f.fn.init.prototype=f.fn;window.addEventListener?window.addEventListener("message",d,!1):window.attachEvent("onmessage",d);return a.Froogaloop=a.$f=f})(vimeowrap);}
