if (typeof vimeowrap === 'undefined') {/*

 Vimeo Wrap

 Author: Wesley Luyten
 Version: 0.1 - (2012/03/18)
*/
var vimeowrap=function(e){return vimeowrap.api.select(e)};
(function(e){var b={};e.api=function(c){function a(a){e.utils.jsonp("http://vimeo.com/api/oembed.json",b({url:a}),function(a){var f=document.createElement("div");f.innerHTML=a.html;d.player=f.children[0];d.player.id=d.config.player_id;e.utils.css(d.player,{position:"absolute",display:"none"});a=function(){e.utils.css(d.player,{display:"block"})};d.player.attachEvent?d.player.attachEvent("onload",a):d.player.onload=a;e.utils.prepend(d.player,d.display);e.Froogaloop(d.player.id).addEvent("ready",function(){d.froogaloop=
e.Froogaloop(d.player.id);d.events.froogaloopReady.dispatch(d.froogaloop)})})}function b(a){for(var c="url,width,maxwidth,height,maxheight,byline,title,portrait,color,callback,autoplay,loop,xhtml,api,wmode,iframe,player_id".split(","),f=0;f<c.length;f++){var k=c[f];d.config.hasOwnProperty(k)&&(a[k]=d.config[k])}return a}var d=this;this.container=c;this.id=c.id;this.config=this.player=this.display=null;this.plugins={};this.videoId=0;this.froogaloop=null;this.setup=function(c){var b={api:!0,player_id:e.utils.uniqueId("player_")};
this.config=e.utils.extend(b,c);d.container.innerHTML="";e.utils.css(d.container,{position:"relative"});d.display=document.createElement("div");d.display.id=d.id+"_display";d.container.appendChild(d.display);e.utils.css(d.display,{width:d.config.width,height:d.config.height,position:"absolute",background:"#000000"});var c=this.config.height,b=0,f;for(f in this.config.plugins)"function"===typeof e[f]&&(this.plugins[f]=new e[f](this,this.config.plugins[f]),this.plugins[f].config.y=c,c+=this.plugins[f].config.height,
"top"===this.plugins[f].config.position&&(this.plugins[f].config.y=b,b+=this.plugins[f].config.height),this.plugins[f].setup());e.utils.css(d.container,{width:d.config.width,height:c});e.utils.css(d.display,{top:b});this.events.playlistFirstLoaded.add(a);(new e.playlistloader(this)).load(this.config.urls)};this.load=function(a,c){if(a.id!==this.videoId){this.pause();e.utils.css(d.player,{display:"none"});"boolean"===typeof c&&(this.config.autoplay=c);this.videoId=a.id;for(var f="http://player.vimeo.com/video/"+
a.id+"?",k="byline,title,portrait,color,autoplay,loop,api,player_id".split(","),l=0;l<k.length;l++){var b=k[l];if(this.config.hasOwnProperty(b)){var h=d.config[b];"boolean"===typeof h&&(h=h?1:0);f+=encodeURIComponent(b)+"="+encodeURIComponent(h)+"&"}}this.player&&(this.player.src=f.slice(0,-1))}};this.playPause=function(){d.froogaloop&&d.froogaloop.api("paused",function(a){!0===a?d.froogaloop.api("play"):d.froogaloop.api("pause")})};this.play=function(){d.froogaloop&&d.froogaloop.api("paused",function(a){!0===
a&&d.froogaloop.api("play")})};this.pause=function(){d.froogaloop&&d.froogaloop.api("paused",function(a){!1===a&&d.froogaloop.api("pause")})};this.events={froogaloopReady:new e.signal,playlistFirstLoaded:new e.signal,playlistAllLoaded:new e.signal}};e.api.select=function(c){var a;c.nodeType?a=c:"string"===typeof c&&(a=document.getElementById(c));return a?(c=b[a.id])?c:b[a.id]=new e.api(a):null}})(vimeowrap);(function(e){e.playlistloader=function(b){function c(){e.utils.jsonp(h.list[d++],{},a)}function a(a){g=g.concat(a);1===d&&(b.events.playlistFirstLoaded.dispatch(g[0].url),b.events.playlistFirstLoaded.remove());d<h.list.length?c():(b.events.playlistAllLoaded.dispatch(g),b.events.playlistAllLoaded.remove())}var h=this,d=0,g=[];this.load=function(a){for(var f=h,d=0;d<a.length;d++)a[d]=a[d].replace(/vimeo.com\/(\d+)$/i,"vimeo.com/api/v2/video/$1.json"),a[d]=a[d].replace(/vimeo.com\/([A-Z][A-Z0-9]+)$/i,
"vimeo.com/api/v2/$1/videos.json");f.list=a;if(a=h.list[0].match(/vimeo.com\/api\/v2\/video\/(\d+)\.json$/))b.events.playlistFirstLoaded.dispatch("http://vimeo.com/"+a[1]),b.events.playlistFirstLoaded.remove();c()}}})(vimeowrap);(function(e){e.utils=function(){};e.utils.jsonp=function(c,a,b){var d="?",a=a||{},g;for(g in a)a.hasOwnProperty(g)&&(d+=encodeURIComponent(g)+"="+encodeURIComponent(a[g])+"&");var j=e.utils.uniqueId("vimeojson");window[j]=function(a){b(a);window[j]=null};var f=document.createElement("script");f.src=c+d+"callback="+j;f.async=!0;f.onload=f.onreadystatechange=function(){if(!this.readyState||"loaded"===this.readyState||"complete"===this.readyState)f.onload=f.onreadystatechange=null,f&&f.parentNode&&f.parentNode.removeChild(f)};
c=document.head||document.getElementsByTagName("head")[0]||document.documentElement;c.insertBefore(f,c.firstChild)};e.utils.extend=function(c,a){for(var b in a)a[b]&&a[b].constructor&&a[b].constructor===Object?(c[b]=c[b]||{},arguments.callee(c[b],a[b])):c[b]=a[b];return c};e.utils.css=function(c,a){if(c)for(var b in a)try{if("undefined"!==typeof a[b]){if("number"==typeof a[b]&&!("zIndex"==b||"opacity"==b)){if(isNaN(a[b]))continue;a[b]=Math.ceil(a[b])+"px"}c.style[b]=a[b]}}catch(d){}};e.utils.prepend=
function(b,a){a.firstChild?a.insertBefore(b,a.firstChild):a.appendChild(b)};var b=0;e.utils.uniqueId=function(c){var a=b++;return c?c+a:a}})(vimeowrap);Array.indexOf||(Array.prototype.indexOf=function(e){for(var b=0;b<this.length;b++)if(this[b]==e)return b;return-1});String.prototype.populate=function(e){return this.replace(/\{\{\s*([^\s}]+)\s*\}\}/g,function(b,c){c=c.replace(/\|/g,"_");return typeof e[c]!=="undefined"?e[c]:b})};(function(e){e.signal=function(){var b=[];this.add=function(c){b.push(c)};this.dispatch=function(){for(var c=Array.prototype.slice.call(arguments),a=0;a<b.length;a++)"function"===typeof b[a]&&b[a].apply(this,c)};this.remove=function(c){if(c)for(var a=0;a<b.length;a++)b[a]===c&&(b.splice(a,1),a--);else b=[]}}})(vimeowrap);/*

 Vimeo Froogaloop
*/
(function(e){function b(a){return new b.fn.init(a)}function c(a,b,d){if(!d.contentWindow.postMessage)return!1;var c=d.getAttribute("src").split("?")[0],a=JSON.stringify({method:a,value:b});"//"===c.substr(0,2)&&(c=window.location.protocol+c);d.contentWindow.postMessage(a,c)}function a(a){var b,c;try{b=JSON.parse(a.data),c=b.event||b.method}catch(e){}"ready"==c&&!g&&(g=!0);if("undefined"===typeof b||a.origin!=j)return!1;var a=b.value,h=b.data,i=""===i?null:b.player_id;b=i?d[i][c]:d[c];c=[];if(!b)return!1;
void 0!==a&&c.push(a);h&&c.push(h);i&&c.push(i);return 0<c.length?b.apply(null,c):b.call()}function h(a,b,c){c?(d[c]||(d[c]={}),d[c][a]=b):d[a]=b}var d={},g=!1,j="";b.fn=b.prototype={element:null,init:function(a){"string"===typeof a&&(a=document.getElementById(a));this.element=a;a=this.element.getAttribute("src");"//"===a.substr(0,2)&&(a=window.location.protocol+a);for(var a=a.split("/"),b="",c=0,d=a.length;c<d;c++){if(3>c)b+=a[c];else break;2>c&&(b+="/")}j=b;return this},api:function(a,b){if(!this.element||
!a)return!1;var d=this.element,e=""!==d.id?d.id:null,g=!b||!b.constructor||!b.call||!b.apply?b:null,i=b&&b.constructor&&b.call&&b.apply?b:null;i&&h(a,i,e);c(a,g,d);return this},addEvent:function(a,b){if(!this.element)return!1;var d=this.element,e=""!==d.id?d.id:null;h(a,b,e);"ready"!=a?c("addEventListener",a,d):"ready"==a&&g&&b.call(null,e);return this},removeEvent:function(a){if(!this.element)return!1;var b=this.element,e;a:{if((e=""!==b.id?b.id:null)&&d[e]){if(!d[e][a]){e=!1;break a}d[e][a]=null}else{if(!d[a]){e=
!1;break a}d[a]=null}e=!0}"ready"!=a&&e&&c("removeEventListener",a,b)}};b.fn.init.prototype=b.fn;window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent("onmessage",a);return e.Froogaloop=e.$f=b})(vimeowrap);}
